apiVersion: v1
kind: Service
metadata:
  name: industryapp-service
spec:
  type: NodePort
  selector:
    app: industryapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30018